basic_app/urls.py
from django.contrib import admin
from django.urls import path,include
from tracker_app import views

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('admin/', admin.site.urls),
    path('tracker_app/',include('tracker_app.urls')),
    path('logout/',views.user_logout,name='logout')
]

tracker_app/urls.py
from django.urls import path
from tracker_app import views

app_name='tracker_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('userinfo/',views.userinfo,name='userinfo'),
    path('vieweffort/',views.vieweffort,name='vieweffort'),
    path('listeffort/',views.listeffort,name='listeffort'),
    path('recordeffort/',views.recordeffort,name='recordeffort'),
    path('generatereport/',views.generatereport,name='generatereport'),
    path('reporttemplate/',views.reporttemplate,name='reporttemplate'),
    path('reporttemplateinfo/',views.reporttemplateinfo,name='reporttemplateinfo'),
    path('deleteeffort/',views.deleteeffort,name='deleteeffort'),
    path('userrecord/',views.userrecord,name='userrecord'),
    path('password/',views.change_password,name='change_password'),
]

tracker_app/models.py
from django.db import models
from django.contrib.auth.models import User
from rest_framework import serializers

# Create your models here.

PROJECT_STATUS_ENUM_CHOICES = (
    ('0', 'to start'),
    ('1', 'ongoing'), 
    ('2', 'ended'), 
    ('3', 'other'), 
)

class UserRegistration(models.Model):
    def __init__(self):
        user=models.OneToOneField(User)

    def __str__(self):
        return self.user.username
        
class ProjectWork(models.Model):
    pwID = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=260)
    work_package = models.CharField(max_length=260, blank=True, default='')
    status = models.CharField(choices=PROJECT_STATUS_ENUM_CHOICES, default='1', max_length=10)
    
    def __str__(self):
        if(len(self.work_package)>0):
            return "%s: %s (%05d)" % (self.project_name, self.work_package, self.pwID)
        else:
            return "%s (%05d)" % (self.project_name, self.pwID)

class WorkEffort(models.Model):
    user_name=models.ForeignKey(User, on_delete=models.CASCADE)
    project_work=models.ForeignKey(ProjectWork, on_delete=models.CASCADE)
    work_date=models.DateField()
    work_hours=models.DecimalField(max_digits=4, decimal_places=1)
    work_issue=models.TextField(blank=True, default='')
    
class WorkEffortSerializer(serializers.ModelSerializer):
    class Meta:
        model = WorkEffort
        fields = ('id', 'project_name', 'work_package', 'work_date', 'work_hours', 'work_issue')

    project_name = serializers.SerializerMethodField()
    work_package = serializers.SerializerMethodField()

    def get_project_name(self, obj):
        return obj.project_work.project_name
            
    def get_work_package(self, obj):
        return obj.project_work.work_package

tracker_app/forms.py
from django import forms
from django.contrib.auth.models import User
from tracker_app.models import UserRegistration, ProjectWork, WorkEffort
from datetime import date

class UserRegistrationForm(forms.ModelForm):
    first_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Firstname'}))
    last_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Lastname'}))
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

    class Meta():
        model=User
        fields=('first_name','last_name','username','password')

class WorkEffortsForm(forms.ModelForm):
    project_work = forms.ModelChoiceField(queryset=ProjectWork.objects.all())
    
    #project_name=forms.CharField(max_length=260,widget=forms.TextInput(attrs={'class':'form-control form-control-sm'}))
    #work_package=forms.CharField(max_length=260,widget=forms.TextInput(attrs={'class':'form-control form-control-sm'}))
    
    work_date=forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date','class':'form-control form-control-date'}))
    work_hours=forms.CharField(max_length=8,widget=forms.NumberInput(attrs={'class':'form-control form-control-sm'}))
    work_issue=forms.CharField(required=False, widget=forms.Textarea(attrs={'class':'form-control form-control-sm form-control-textarea'}))

    class Meta():
        model=WorkEffort
        exclude=('user_name',)

class ViewUserEffortForm(forms.ModelForm):

    class Meta():
        model=WorkEffort
        fields=('user_name',)

tracker_app/views.py
from django.shortcuts import render,redirect
from tracker_app.forms import UserRegistrationForm, WorkEffortsForm, ViewUserEffortForm
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.urls.base import reverse
from django.contrib.auth  import login,logout,authenticate
from django.forms import *
from tracker_app.models import User, UserRegistration, WorkEffort, WorkEffortSerializer
from django.db.models import Q

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

# Create your views here.

# @login_required
def user_logout(request):
    logout(request)
    return redirect('/login/')


def user_login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request,username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)

                session_user={'id':user.id,'username':user.username,'first_name':user.first_name.upper(),'last_name':user.last_name.upper(),'is_superuser':user.is_superuser}
                # user_logged=User.objects.values()
                # print(user_logged);
                request.session['session_user']=session_user
                user_form=WorkEffortsForm()
                user_dict={
                'v_firstname':session_user['first_name'],
                'v_lastname':session_user['last_name'],
                'is_superuser':session_user['is_superuser'],
                'form':user_form
                }

                return render(request,'tracker_app/userpage.html',user_dict)

                # return redirect('/tracker_app/userinfo')
            else:
                raise forms.ValidationError("You user account is not active!")
        else:
            return render(request,'tracker_app/login.html',{'v_error':'Username/Password incorrect!!'})
    else:
        return render(request,'tracker_app/login.html')


def register(request):
    registration_page=True
    registered=False
    if request.method=='POST':
        user_registerform=UserRegistrationForm(request.POST)
        if user_registerform.is_valid:
            user=user_registerform.save(commit=False)
            user.set_password(user.password)
            user.save()
            registered=True
        else:
            print(user_registerform.errors)
    else:
        user_registerform=UserRegistrationForm()


    return render(request,'tracker_app/register.html',context={'user_form':user_registerform,'registered':registered,'registration_page':registration_page})

@login_required
def userinfo(request):

    #get the user session info
    session_user=request.session.get('session_user')
    user_form=WorkEffortsForm()
    user_dict={
    'v_firstname':session_user['first_name'],
    'v_lastname':session_user['last_name'],
    'is_superuser':session_user['is_superuser'],
    'form':user_form
    }

    return render(request,'tracker_app/userpage.html',user_dict)

@login_required
def vieweffort(request):
    session_user=request.session.get('session_user')
    user_list=ViewUserEffortForm()
    user_dict={
    'v_firstname':session_user['first_name'],
    'v_lastname':session_user['last_name'],
    'is_superuser':session_user['is_superuser'],
    'user_list':user_list

    }
    return render(request,'tracker_app/viewefforts.html',user_dict)

@csrf_exempt
def listeffort(request):
    session_user=request.session.get('session_user')
    effort_list=[]
    from_date=request.POST['fromdate']
    to_date=request.POST['todate']

    if len(list(request.POST))>2:
        if from_date=="" and to_date=="":
            effort_list=WorkEffort.objects.filter(user_name_id=request.POST['user_id'],project_work__status="1")
        else:
            effort_list=WorkEffort.objects.filter(work_date__gte=from_date,work_date__lte=to_date,user_name_id=request.POST['user_id'],project_work__status="1")
    else:
        if from_date=="" and to_date=="":
            effort_list=WorkEffort.objects.filter(user_name_id=session_user['id'],project_work__status="1")
        else:
            effort_list=WorkEffort.objects.filter(work_date__gte=from_date, work_date__lte=to_date, user_name_id=session_user['id'],project_work__status="1")

    effort_list = WorkEffortSerializer(effort_list, many=True).data
    return JsonResponse(effort_list ,safe=False)

@csrf_exempt
def recordeffort(request):
    session_user=request.session.get('session_user')
    effortform=WorkEffortsForm(request.POST)
    if effortform.is_valid():
        usereffort=effortform.save(commit=False)
        usereffort.user_name=User.objects.get(username=session_user['username'])
        usereffort.save()
        print('form is valid and saved')
        status='Record has been saved sucessfully'
        ind=0

    else:
        print('form is not valid')
        #status='Please check your details entered!!!'
        status=str(effortform.errors)
        ind=1

    return JsonResponse({'Message':status,'IND':ind})

@login_required
def generatereport(request):
    session_user=request.session.get('session_user')
    user_dict= {
     'v_firstname':session_user['first_name'],
     'v_lastname':session_user['last_name'],
     'is_superuser':session_user['is_superuser'],
     }
    return render(request,'tracker_app/report.html',user_dict)

def reporttemplate(request):
    session_user=request.session.get('session_user')
    context_dict= {
     'v_firstname':session_user['first_name'],
     'v_lastname':session_user['last_name'],
     }

    return render(request,'tracker_app/report_template.htm',context_dict)

@csrf_exempt
def reporttemplateinfo(request):
    session_user=request.session.get('session_user')
    from_date=request.POST['fromdate']
    to_date=request.POST['todate']
    print(from_date,to_date)
    if from_date=="" and to_date=="":
        effort_list=WorkEffort.objects.filter(user_name_id=session_user['id'])
    else:
        effort_list=WorkEffort.objects.filter(work_date__gte=from_date,work_date__lte=to_date,user_name_id=session_user['id'])


    for colitems in ["work_date"]:
        dates =list(effort_list.order_by('work_date').values(colitems))
        print(dates)
        #Creating row span for Date
        eff={}
        i=0
        rowspan=1
        for items in dates:

            if i== len(dates)-1 :
                eff[str(dates[i][colitems])]=rowspan
            else:
                if dates[i][colitems]==dates[i+1][colitems]:
                    rowspan+=1
                else:
                    eff[str(dates[i][colitems])]=rowspan
                    rowspan=1
                i+=1




    return JsonResponse([eff,list(effort_list.values())],safe=False)

@csrf_exempt
def deleteeffort(request):
    userEffortDelete=WorkEffort.objects.get(id=request.POST['delete_id'])
    if userEffortDelete.delete():
        return HttpResponse("Record deleted successfully")
    else:
        return HttpResponse("Error deleting record")

def userrecord(request):
    user_logged=User.objects.values()
    return JsonResponse(list(user_logged),safe=False)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'tracker_app/change_password.html', {
        'form': form
    })

templates/tracker_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Effort Tracker</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-grid.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-grid.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-reboot.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-reboot.min.css" %}">
    <link rel="stylesheet" href="{%static "css/style.css"%}">
    <link rel="stylesheet" href="{%static "css/jquery.dataTables.min.css"%}">
    <link rel="stylesheet" href="{%static "css/fonts.css"%}">
	<link href="{%static "images/icons8-training-40.png"%}" rel="shortcut icon">

  </head>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModal">Confirm Remove Effort</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to remove the record ?
        </div>
        <div class="modal-footer">
          <button type="button" id="confirm-yes" class="btn btn-secondary" data-dismiss="modal">Yes</button>
          <button type="button" id="confirm-no"  data-dismiss="modal" class="btn btn-primary">Cancel</button>
        </div>
      </div>
    </div>
  </div>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- <a class="navbar-brand" href="">Effort Tracker</a> -->

    <div class="navbar-nav">

       {% if user.is_authenticated %}
         {% if is_superuser%}
         <a class="nav-item nav-link" href="/admin/">Admin<span class="sr-only">(current)</span></a>
          {% endif %}
       <a class="nav-item nav-link" href="{% url 'tracker_app:userinfo' %}">Records Efforts<span class="sr-only">(current)</span></a>
       <a class="nav-item nav-link" href="{% url 'tracker_app:vieweffort' %}">View Efforts<span class="sr-only">(current)</span></a>
       <a class="nav-item nav-link" href="{% url 'tracker_app:generatereport' %}">Generate Report<span class="sr-only">(current)</span></a>
       <a class="nav-item nav-link" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
       <a class="nav-item nav-link" href="{% url 'tracker_app:change_password' %}">Change Password<span class="sr-only">(current)</span></a>
       {%else %}
        {% if registration_page%}
        <a class="nav-item nav-link" href="{% url 'login' %}">Already registered ? Goto Login<span class="sr-only">(current)</span></a>
        {%else %}
        <a class="nav-item nav-link" href="{% url 'tracker_app:register' %}">Click here to register</a>
        <!-- <a class="nav-item nav-link" href="/admin/">Admin<span class="sr-only">(current)</span></a> -->
       {% endif %}


       {% endif %}

   </div>
 </nav>
  {% block body_block%}
  {% endblock %}

  <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js"%}">
  </script>
  <script type="text/javascript" src="{% static "js/jquery.dataTables.min.js"%}">
  </script>
  <script type="text/javascript" src="{% static "js/bootstrap.bundle.js"%}">
  </script>
  <script type="text/javascript" src="{% static "js/main.js"%}">
  </script>

  </body>
  </html>

templates/tracker_app/change_password.html
{% extends 'tracker_app/base.html' %}

{% block body_block %}
<body class="{% block body_class %}nonlogin{% endblock %}">

<div class="container">
  <div class="jumbotron home-page">
    <h6>Welcome {{v_firstname}} {{v_lastname}}</h6>
    <p style="display:none;" >
      <h6 id="alert" ></h6>
    </p>

  </div>

<div id="effort-form">
   <!-- <form> -->
  {% csrf_token %}
  {{form.as_p}}
  
  <button type="submit">Save changes</button>
  <!-- </form> -->

</div>

</div>

{% endblock %}

templates/tracker_app/index.html
{% extends 'tracker_app/base.html' %}
{% block body_block %}



<div class="wrapper">




      <h5>Welcome to Effort Tracker application</h5>


</div>

{% endblock %}

templates/tracker_app/login.html
{% extends 'tracker_app/base.html' %}
{% block body_block %}
<!-- <div class="login-page"> -->

      <div class="wrapper rounded">
  <div class="bg"></div>
          <!-- {% if v_error %} -->
          <div class="login-alert" role="alert">
            <p>{{v_error}}</p>
          <!--  -->
          </div>
          <!-- {% endif %} -->
          <div class="sm-margin">
            <h3>Effort Tracker</h3>
          </div>
          <form  method="POST">
            {% csrf_token %}
            <div class="form-group">

            <input type="text" class="form-control" name="username" id="Username" aria-describedby="emailHelp" placeholder="Username" required>
            </div>
            <div class="form-group">

            <input type="password"  class="form-control" name="password" id="Password" placeholder="Password" required>
            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>

          </form>

        </div>

<!-- </div> -->


{% endblock %}

templates/tracker_app/register.html
{% extends 'tracker_app/base.html' %}
{% block body_block %}
    <div class="container success-page">
      {% if registered %}
          <h1 style="font-weight:900px;font-size:52px;color:#0c0e0ccc;">Successfully Registered</h1>
      {%else%}

    <h3 style="font-weight:500px;font-size:35px;color:#0c0e0ccc;">Please enter your registration details</h3>

    <form method="post">
      {% csrf_token %}
      <div class="">
        {{user_form.first_name}}
        {{user_form.last_name}}
      </div>
      <div class="">
        {{user_form.username}}
      </div>
      <div class="">
        {{user_form.password}}
      </div>
      <div class="">
        <input type="password" id="confirm-pass" data-toggle="tooltip" title="Re-enter your password" name="confirm" value="" placeholder="Confirm Password">
        <!-- <span id="confirm-password-alert"></span> -->
      </div>

      <input id="Register" class="btn btn-primary" type="submit" name="Register" value="Register" disabled>

    </form>

    </div>
    {%endif %}


{% endblock %}

templates/tracker_app/report.html
{% extends 'tracker_app/base.html' %}
{% load staticfiles %}
{% block body_block %}
<body class="{% block body_class %}nonlogin{% endblock %}">
  <script type="text/javascript" src="{% static "js/jspdf.debug.js"%}">
  </script>

<div class="container">
  <h6>{{v_firstname}} {{v_lastname}}, Please select period to be generated</h6>

  <div class="date-class">
    <label>Period From</label>
    <label>Period To</label>
  </div>
  <div class="report-options">
    <input type="date" id="fromperiod" name="fromperiod" value="">
    <input type="date" id="toperiod" name="fromperiod" value="">

    <input type="button" id="generateBtn" class="btn btn-primary" name="generate" value="Generate Report" style="display:none;">
    <!-- <input type="button" id="downloadBtn" class="btn btn-primary" name="download" value="Download Report" style="display:none;" data-toggle="popover" data-placement="bottom" title='<ul><li><a href="#">PDF</a></li><li><a href="#">Excel</a></li><li><a href="#">MS Word</a></li></ul>'> -->
    <!-- Example single danger button -->
    <div class="btn-group dropbottom" id="downloadBtn" style="display:none;">
    <input type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" name="download" value="Download Report">

      <div class="dropdown-menu">
        <a class="dropdown-item" href="#" onclick="Export2PDF('report-template');">PDF</a>
        <a class="dropdown-item" href="#" onclick="Export2Doc('report-template');">MS Word</a>

      </div>
    </div>
  </div>





      <div class="report-frame">
        <iframe class="awindow" name="awindow" id="awindow" style="display:None;" frameborder=2 src="/tracker_app/reporttemplate/"></iframe>
      </div>










{% endblock %}

templates/tracker_app/report_template.htm
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{%static "css/mystyle.css"%}">
  </head>
  <body class="report-class">
    <div class="report-template">

            <h2>WEEKLY PROGRESS REPORT</h2>
            <table style="border-collapse:collapse;">
              <tr>
                <td style="border: 1px solid black;padding:2px 5px;">Name:</td>
                <td style="border: 1px solid black;padding:2px 5px;">{{v_firstname}} {{v_lastname}}</td>
              </tr>
              <tr>
                <td style="border: 1px solid black;padding:2px 5px;">Designation:</td>
                <td style="border: 1px solid black;padding:2px 5px;">Test Engineer</td>
              </tr>
              <tr>
                <td style="border: 1px solid black;padding:2px 5px;">Section:</td>
                <td style="border: 1px solid black;padding:2px 5px;">Fare Systems</td>
              </tr>
              <tr >
                <td style="border: 1px solid black;padding:2px 5px;">Reporting Period:</td>
                <td style="border: 1px solid black;padding:2px 5px;" id ="reporting-period"></td>

              </tr>

              <tr>
                <td style="border: 1px solid black;padding:2px 5px;">Reporting Officer:</td>
                <td style="border: 1px solid black;padding:2px 5px;">Sukalpa Raghukumar</td>
              </tr>
              <tr>
                <td style="border: 1px solid black;padding:2px 5px;">Leave(s) Taken During
        Reporting Period:</td>
                <td style="border: 1px solid black;padding:2px 5px;">None</td>
              </tr>

            </table>

        <h3>A.	ACHIEVEMENTS IN THE REPORTING WEEK </h3>
        <table style="border-collapse: collapse;" id="effort-table">

          <thead>
            <td style="border: 1px solid black;padding:2px 5px;">Dates</td>
            <td style="border: 1px solid black;padding:2px 5px;">Project Name</td>
            <td style="border: 1px solid black;padding:2px 5px;">task Name</td>
            <td style="border: 1px solid black;padding:2px 5px;">Work Done</td>
            <td style="border: 1px solid black;padding:2px 5px;">Worked Hours</td>
          </thead>
          <tbody>

          </tbody>

        </table>
        <h3>B.	ACTION PLAN FOR THE FOLLOWING WEEK</h3>
        <table style="border-collapse: collapse;">
          <thead>
            <td style="border: 1px solid black;padding:2px 5px;">Dates</td>
            <td style="border: 1px solid black;padding:2px 5px;">Project Name</td>
            <td style="border: 1px solid black;padding:2px 5px;">Task Name</td>
            <td style="border: 1px solid black;padding:2px 5px;">Work to be done</td>
          </thead>
          <tbody>
            <tr>
              <td style="border: 1px solid black;width:120px;height:50px;"></td>
              <td style="border: 1px solid black;width:120px;height:50px;"></td>
              <td style="border: 1px solid black;width:120px;height:50px;"></td>
              <td style="border: 1px solid black;width:120px;height:50px;"></td>
  </tr>
          </tbody>


        </table>
        <h3>PROBLEMS ENCOUNTERED / INTERESTING FINDINGS</h3>
          <ul>
            <li>NIL</li>
          </ul>
        <h3>C.	OTHER ISSUES </h3>
        <ul>
          <li>NIL</li>
        </ul>
    </div>

  </body>

</html>

templates/tracker_app/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Effort Tracker</title>
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_appC:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/bootstrap.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/bootstrap-grid.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/bootstrap-reboot.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/css/style.css">


  </head>
  <body>
    <table id="usertable" class="table table-striped"><thead class="thead-dark"><tr><th scope="col">Action</th><th scope="col">Project</th><th scope="col">Task</th><th scope="col">Work done</th><th scope="col">Date</th><th scope="col">Hours Worked</th><th scope="col">Problems faced</th></tr></thead><tbody><tr scope="row"><td><span onclick="deleterow(this.id)" id="11" class="badge badge-dark">Delete</span></td><td>Full ABT</td><td>BS32 Phase 2 UAT</td><td>SIT transaction Generation</td><td>2018-01-01</td><td>4.0</td><td>asssd</td></tr><tr scope="row"><td><span onclick="deleterow(this.id)" id="15" class="badge badge-dark">Delete</span></td><td>ABT phase2</td><td>asas</td><td>mn,m,,</td><td>2018-02-01</td><td>7.0</td><td>hkljljl</td></tr><tr scope="row"><td><span onclick="deleterow(this.id)" id="19" class="badge badge-dark">Delete</span></td><td>ABT Phase 1</td><td>SIT</td><td>Transaction generation</td><td>2018-07-17</td><td>4.0</td><td>No one has knowledge on modules</td></tr><tr scope="row"><td><span onclick="deleterow(this.id)" id="21" class="badge badge-dark">Delete</span></td><td>Full ABT</td><td>BS32 Phase 2 UAT</td><td>blk 674 hougang</td><td>2018-07-04</td><td>6.0</td><td>asasas</td></tr><tr scope="row"><td><span onclick="deleterow(this.id)" id="23" class="badge badge-dark">Delete</span></td><td>Full ABT</td><td>dsad</td><td>sadsad</td><td>2018-07-04</td><td>6.0</td><td>sdad</td></tr></tbody></table>
  </body>
  <script type="text/javascript" src="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/js/jquery-3.3.1.min.js">
    </script>
    <script type="text/javascript" src="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/js/jquery.dataTables.min.js">
    </script>
    <script type="text/javascript" src="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/js/bootstrap.bundle.js">
    </script>
    <script type="text/javascript" src="C:/Users/DELL/Desktop/Jameer/Python/Web%20development/Djangofiles/basic_app/static/js/main.js">
    </script>
    <script type="text/javascript">
    $(document).ready(function() {
        $('#usertable').DataTable();
    });
</script>
</html>

templates/tracker_app/userpage.html
{% extends 'tracker_app/base.html' %}

{% block body_block %}
<body class="{% block body_class %}nonlogin{% endblock %}">

<div class="container">
  <div class="jumbotron home-page">
    <h6>Welcome {{v_firstname}} {{v_lastname}}</h6>
    <p style="display:none;" >
      <h6 id="alert" ></h6>
    </p>

  </div>

<div id="effort-form">
   <!-- <form> -->
    {% csrf_token %}
    {{form.as_p}}

    <input id="record-submit" type="button" class="btn btn-primary" name="" value="Record Effort ">
    <input id="cancelEntry" type="button" class="btn btn-primary" name="" value="Cancel">

  <!-- </form> -->

</div>

</div>

{% endblock %}